name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Frontend CI
        working-directory: ./web
        run: |
          npm ci
          npm run lint
          npm test
          npm run build

      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./web/.next
          include-hidden-files: true
    
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: back/package-lock.json

      - name: Backend CI
        working-directory: ./back
        run: |
          npm ci
          npm run lint
          npm test
  
  build:
    needs:
      - frontend
      - backend
    runs-on: ubuntu-latest

    steps:
      - name: Download Frontend Build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./web/.next

      - name: Show Frontend Build
        run: ls -la ./web/.next