name: My First Workflow
on:
  push:
    branches:
      - master

env:
  APP_NAME: "This is a global variable"

jobs:
 test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Install Frontend dependencies
        working-directory: ./web
        run: npm ci

      - name: Install Backend dependencies
        working-directory: ./back
        run: npm ci
      
      - name: Front Lint
        working-directory: ./web
        run: npm run lint

      - name: Front Test
        if: success()
        working-directory: ./web
        run: npm test
      
      - name: Back Lint
        working-directory: ./back
        run: npm run lint

      - name: Back Test
        if: success()
        working-directory: ./back
        run: npm test


      - name: Backend Smoke Test
        if: success()
        working-directory: ./back
        run: npm run smoke
      
        
      