name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Frontend CI
        working-directory: ./web
        run: |
          npm ci
          npm run lint
          npm test
          npm run build

      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./web/.next
          include-hidden-files: true
    
  backend:
    runs-on: ubuntu-latest
    environment: dev


    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      PORT: ${{ vars.PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: back/package-lock.json

      - name: Backend CI
        working-directory: ./back
        run: |
          npm ci
          npm run lint
          npm test

      - name: Check environment variables
        run: |
          if [ -n "$JWT_SECRET" ]; then
            echo "JWT_SECRET is set"
          else
            echo "JWT_SECRET is NOT set"
            exit 1
          fi

          if [ -n "$JWT_EXPIRES_IN" ]; then
            echo "JWT_EXPIRES_IN is set"
          else
            echo "JWT_EXPIRES_IN is NOT set"
            exit 1
          fi

          if [ -n "$PORT" ]; then
            echo "PORT is set"
          else
            echo "PORT is NOT set"
            exit 1
          fi
      - name: Success Test
        if: success()
        run: echo "Backend job is successful"

      - name: Failure Test
        if: failure()
        run: echo "Backend job has failed"

      - name: Always Test
        if: always()
        run: echo "This step always runs"